const { test, expect } = require('@playwright/test');
test('sound library plays separate initial and final clips only on tap',async({page})=>{
  const requests=[];page.on('request',r=>requests.push(r.url()));
  await page.goto('./');
  expect(requests.filter(u=>u.includes('opencantonese.org'))).toEqual([]);
  await page.locator('#sounds-panel > summary').click();
  await expect(page.locator('#initial-sounds button')).toHaveCount(19);
  await page.getByRole('button',{name:'聽聲母 b',exact:true}).click();
  const player=page.locator('#sound-player');
  await expect(player).toHaveAttribute('src',/initial-01-b.mp3$/);
  await expect.poll(()=>player.evaluate(e=>e.readyState)).toBeGreaterThanOrEqual(2);
  await expect.poll(()=>player.evaluate(e=>e.paused)).toBe(false);
  await page.getByRole('button',{name:'聽韻母 aa',exact:true}).click();
  await expect(player).toHaveAttribute('src',/final-01-aa.mp3$/);
  await expect.poll(()=>player.evaluate(e=>e.readyState)).toBeGreaterThanOrEqual(2);
  await expect.poll(()=>player.evaluate(e=>e.paused)).toBe(false);
  await page.locator('#sound-slow').check();
  expect(await player.evaluate(e=>e.playbackRate)).toBe(0.75);
  await page.locator('#sound-stop').click();expect(await player.evaluate(e=>e.paused)).toBe(true);
  await expect(page.locator('#sound-source')).toHaveAttribute('href',/^https:\/\/opencantonese.org\/books\//);
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
test('sound loading failure is recoverable and does not block flashcards',async({page})=>{
 await page.route('https://opencantonese.org/files/**/*.mp3',route=>route.abort());
 await page.goto('./');await page.locator('#sounds-panel > summary').click();
 await page.getByRole('button',{name:'聽聲母 ng',exact:true}).click();
 await expect(page.locator('#sound-status')).toContainText(/播唔到|未能載入/);
 await page.locator('#answer').fill('夏天');await page.locator('#check').click();
 await expect(page.locator('#feedback')).toContainText('啱');
});
test('personal flashcards create, flip, edit, practise, persist and delete safely' ,async({page})=>{
  await page.goto('./');
  await page.getByText('自訂 Flashcards',{exact:true}).click();
  await page.locator('#custom-text').fill('地衣');
  await page.locator('#custom-jyutping').fill('dei6 ji1');
  await page.locator('#custom-note').fill('自己想記嘅字');
  await page.locator('#custom-save').click();
  await expect(page.locator('#custom-list summary')).toHaveText('地衣');
  await page.locator('#custom-list summary').click();
  await expect(page.locator('#custom-list')).toContainText('dei6 ji1');
  await page.getByRole('button',{name:'編輯',exact:true}).click();
  await page.locator('#custom-note').fill('更新備註');
  await page.locator('#custom-save').click();
  await page.reload();
  await page.getByText('自訂 Flashcards',{exact:true}).click();
  await page.locator('#custom-list summary').click();
  await expect(page.locator('#custom-list')).toContainText('更新備註');
  await page.locator('#custom-practice').click();
  await expect(page.locator('#target')).toHaveText('地衣');
  await page.locator('#mode').selectOption('spelling');
  await page.locator('#answer').fill('dei ji');await page.locator('#check').click();
  await expect(page.locator('#feedback')).toContainText('拼啱');
  page.once('dialog',d=>d.accept());
  await page.getByRole('button',{name:'刪除',exact:true}).click();
  await expect(page.locator('#custom-list')).toContainText('未有自訂卡');
  const data=await page.evaluate(()=>JSON.parse(localStorage.getItem('jyutping-practice-v1')));
  expect(data.custom).toEqual([]);expect(data.records.spelling).toEqual({});
});
test('custom cards round-trip backup, export TSV, reject bad inputs and explain unavailable voice',async({page})=>{
  await page.goto('./');await page.locator('#custom-panel summary').first().click();
  await page.locator('#custom-text').fill('地衣');await page.locator('#custom-jyutping').fill('dei ji');await page.locator('#custom-save').click();
  await expect(page.locator('#custom-status')).toContainText('未儲存');
  await page.locator('#custom-jyutping').fill('dei6 ji1');await page.locator('#custom-note').fill('<script>notes</script>');await page.locator('#custom-save').click();
  await expect(page.locator('#custom-list summary')).toHaveText('地衣');
  await page.locator('#custom-practice').click();
  await page.evaluate(()=>{window.speechSynthesis.getVoices=()=>[];});
  await page.locator('#listen').click();await expect(page.locator('#audio-status')).toContainText('未有本機廣東話聲線');
  await expect(page.locator('#pronunciation')).not.toHaveAttribute('src',/custom-/);
  await page.locator('#answer').fill('地衣');await page.locator('#check').click();
  const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('jyutping-practice-v1')));
  const tsvDownload=page.waitForEvent('download');await page.locator('#custom-export').click();
  const tsv=await tsvDownload;expect(tsv.suggestedFilename()).toBe('my-jyutping-flashcards.tsv');
  const fs=require('fs');expect(fs.readFileSync(await tsv.path(),'utf8')).toBe('地衣\tdei6 ji1\t&lt;script&gt;notes&lt;/script&gt;');
  await page.getByText('進度與備份',{exact:true}).click();
  const dlPromise=page.waitForEvent('download');await page.locator('#export').click();const dl=await dlPromise;
  expect(JSON.parse(fs.readFileSync(await dl.path(),'utf8'))).toEqual(saved);
  await page.evaluate(()=>localStorage.clear());await page.reload();
  await page.getByText('進度與備份',{exact:true}).click();page.once('dialog',d=>d.accept());
  await page.locator('#import').setInputFiles({name:'custom.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(saved))});
  await expect(page.locator('#storage-status')).toHaveText('已匯入備份。');
  expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('jyutping-practice-v1')))).toEqual(saved);
  await page.locator('#custom-panel summary').first().click();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
});
test('each card plays real Cantonese audio at normal and slow speed without exposing spelling', async ({page}) => {
  await page.goto('./');
  await page.locator('#listen').click();
  const player=page.locator('#pronunciation');
  await expect.poll(()=>player.evaluate(e=>e.readyState)).toBeGreaterThanOrEqual(2);
  await expect.poll(()=>player.evaluate(e=>e.paused)).toBe(false);
  expect(await player.evaluate(e=>e.duration)).toBeGreaterThan(0.2);
  await expect(player).toHaveAttribute('src',/audio\/structure-1.mp3$/);
  await expect(page.locator('#solution')).toBeHidden();
  await page.locator('#slow').click();
  expect(await player.evaluate(e=>e.playbackRate)).toBe(0.75);
  await page.locator('#next').click();
  expect(await player.evaluate(e=>e.paused)).toBe(true);
  await expect(player).toHaveAttribute('src',/audio\/structure-2.mp3$/);
  await page.locator('#listen').click();
  await expect.poll(()=>player.evaluate(e=>e.paused)).toBe(false);
  expect(await player.evaluate(e=>e.playbackRate)).toBe(1);
  await expect(page.locator('#audio-note')).toContainText('合成');
});
test('TypeDuck target, blank answer, wrong answer, hint, correct text, reload persistence', async ({page}) => {
  await page.goto('./');
  await expect(page.locator('#target')).toHaveText('夏天');
  await expect(page.locator('#solution')).toBeHidden();
  await page.locator('#check').click();
  await expect(page.locator('#feedback')).toContainText('先輸入');
  await expect(page.locator('#attempts')).toHaveText('0');
  await page.locator('#answer').fill('冬天');
  await page.locator('#check').click();
  await expect(page.locator('#feedback')).toContainText('未啱');
  await expect(page.locator('#solution')).toBeVisible();
  await page.locator('#answer').fill('夏天');
  await page.locator('#check').click();
  await expect(page.locator('#feedback')).toContainText('打啱');
  await page.reload();
  await expect(page.locator('#attempts')).toHaveText('1');
  const data = await page.evaluate(() => JSON.parse(localStorage.getItem('jyutping-practice-v1')));
  expect(data.records.typing['structure-1'].mistakes).toBe(1);
});

test('spelling, tone toggle and per-mode records remain distinct', async ({page}) => {
  await page.goto('./');
  await page.locator('#mode').selectOption('spelling');
  await page.locator('#answer').fill('haa tin');
  await page.locator('#check').click();
  await expect(page.locator('#feedback')).toContainText('拼啱');
  await page.locator('#tones').check();
  await page.locator('#answer').fill('haa tin');
  await page.locator('#check').click();
  await expect(page.locator('#feedback')).toContainText('未啱');
  await page.locator('#answer').fill('haa6 tin1');
  await page.locator('#check').click();
  await expect(page.locator('#feedback')).toContainText('拼啱');
  const data = await page.evaluate(() => JSON.parse(localStorage.getItem('jyutping-practice-v1')));
  expect(data.records.spelling['structure-1'].streak).toBe(1);
  expect(data.records.tones['structure-1'].streak).toBe(0);
  expect(data.records.typing).toEqual({});
});
test('hints do not advance mastery and IME composition does not grade', async ({page}) => {
  await page.goto('./');
  await page.locator('#hint').click();
  await expect(page.locator('#solution')).toContainText('h + …');
  await page.locator('#answer').fill('夏天');
  await page.locator('#answer').dispatchEvent('compositionstart');
  await page.locator('#check').click();
  await expect(page.locator('#attempts')).toHaveText('0');
  await page.locator('#answer').dispatchEvent('compositionend');
  await page.locator('#check').click();
  const data=await page.evaluate(() => JSON.parse(localStorage.getItem('jyutping-practice-v1')));
  expect(data.records.typing['structure-1'].streak).toBe(0);
  await page.locator('#next').click();
  await expect(page.locator('#target')).toHaveText('今天');
});
test('export/import round trip, bad import preservation, no third-party requests or errors', async ({page}) => {
  const errors=[]; const external=[];
  page.on('pageerror',e=>errors.push(e.message));
  page.on('request',r=>{if(!r.url().startsWith(new URL(page.context()._options.baseURL).origin))external.push(r.url());});
  await page.goto('./');
  await page.locator('#answer').fill('夏天'); await page.locator('#check').click();
  await page.getByText('進度與備份',{exact:true}).click();
  const downloadPromise=page.waitForEvent('download'); await page.locator('#export').click();
  const download=await downloadPromise;
  const file=await download.path();
  const before=await page.evaluate(()=>localStorage.getItem('jyutping-practice-v1'));
  await page.locator('#import').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{"version":77}')});
  await expect(page.locator('#storage-status')).toContainText('原有進度冇改動');
  expect(await page.evaluate(()=>localStorage.getItem('jyutping-practice-v1'))).toBe(before);
  page.once('dialog',d=>d.accept()); await page.locator('#reset').click();
  await expect(page.locator('#attempts')).toHaveText('0');
  page.once('dialog',d=>d.accept()); await page.locator('#import').setInputFiles(file);
  await expect(page.locator('#storage-status')).toHaveText('已匯入備份。');
  await expect(page.locator('#attempts')).toHaveText('1');
  expect(errors).toEqual([]);expect(external).toEqual([]);
});
test('narrow and landscape layouts fit viewport; lesson video has timestamp', async ({page}) => {
  await page.goto('./');
  await page.locator('#lesson').selectOption('eo');
  await expect(page.locator('#video')).toHaveAttribute('href',/t=2356s$/);
  for(const size of [{width:320,height:640},{width:844,height:390}]){
    await page.setViewportSize(size);
    expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
    expect(await page.locator('#answer').evaluate(e=>parseFloat(getComputedStyle(e).fontSize))).toBeGreaterThanOrEqual(16);
  }
});
